apiVersion: nais.io/v1alpha1
kind: Application

metadata:
    name: oppgave
    namespace: aap
    labels:
        team: aap
        sub: oppgave

spec:
    ingresses:
        - https://aap-oppgave.intern.dev.nav.no
    image: {{image}}
    strategy:
        type: Recreate
    port: 8080
    replicas:
        max: 1
        min: 1
    resources:
        limits:
            memory: 512Mi
        requests:
            cpu: 500m
            memory: 512Mi
    observability:
        autoInstrumentation:
            enabled: true
            runtime: "java"
        logging:
            destinations:
                - id: elastic
                - id: loki
    prometheus:
        enabled: true
        path: /actuator/metrics
    azure:
        application:
            enabled: true
            allowAllUsers: true
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
    liveness:
        path: /actuator/live
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    readiness:
        path: /actuator/ready
        initialDelay: 5
        periodSeconds: 5
        failureThreshold: 5
    secureLogs:
        enabled: true
    accessPolicy:
        inbound:
            rules:
                - application: behandlingsflyt
                - application: postmottak-backend
                - application: produksjonsstyring
                - application: oppgavestyring-frontend
                - application: azure-token-generator # Ikke i prod :)
                  namespace: aura
                  cluster: dev-gcp
        outbound:
            external:
                - host: pdl-api.dev-fss-pub.nais.io
            rules:
                - application: tilgang
                - application: skjermede-personer-pip
                  namespace: nom
    env:
        - name: INTEGRASJON_TILGANG_URL
          value: http://tilgang
        - name: INTEGRASJON_TILGANG_SCOPE
          value: api://dev-gcp.aap.tilgang/.default
        - name: INTEGRASJON_PDL_URL
          value: https://pdl-api.dev-fss-pub.nais.io
        - name: INTEGRASJON_PDL_SCOPE
          value: api://dev-fss.pdl.pdl-api/.default
        - name: INTEGRASJON_NORG_URL
          value: https://norg2.dev-fss-pub.nais.io
        - name: INTEGRASJON_NOM_URL
          value: http://skjermede-personer-pip.nom
        - name: INTEGRASJON_NOM_SCOPE
          value: api://dev-gcp.nom.skjermede-personer-pip/.default
        - name: MS_GRAPH_BASE_URL
          value: https://graph.microsoft.com/v1.0
        - name: MS_GRAPH_SCOPE
          value: https://graph.microsoft.com/.default
    gcp:
        sqlInstances:
            - type: POSTGRES_16
              tier: db-f1-micro
              databases:
                  - name: oppgave
