isdev: true
ingress: https://aap-oppgave.intern.dev.nav.no
env:
    - name: INTEGRASJON_TILGANG_URL
      value: http://tilgang
    - name: INTEGRASJON_TILGANG_SCOPE
      value: api://dev-gcp.aap.tilgang/.default
    - name: INTEGRASJON_STATISTIKK_URL
      value: http://statistikk
    - name: INTEGRASJON_STATISTIKK_SCOPE
      value: api://dev-gcp.aap.statistikk/.default
    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: INTEGRASJON_PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: INTEGRASJON_NORG_URL
      value: https://norg2.dev-fss-pub.nais.io
    - name: INTEGRASJON_NOM_URL
      value: http://skjermede-personer-pip.nom
    - name: INTEGRASJON_NOM_SCOPE
      value: api://dev-gcp.nom.skjermede-personer-pip/.default
    - name: MS_GRAPH_BASE_URL
      value: https://graph.microsoft.com/v1.0/
    - name: MS_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
    - name: INTEGRASJON_VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io
    - name: INTEGRASJON_VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: INTEGRASJON_VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao
    - name: INTEGRASJON_VEILARBOPPFOLGING_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default