apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: oppgave
  namespace: aap
  labels:
    team: aap
    sub: oppgave

spec:
  ingresses:
    - {{ingress}}
  image: {{image}}
  port: 8080
  resources:
    limits:
      memory: 1GB
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          {{#each groups}}
            - id: {{this.group}}
          {{/each}}
  liveness:
    path: /actuator/live
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  readiness:
    path: /actuator/ready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 5
  envFrom:
    - secret: {{unleash_secret}}
  accessPolicy:
    inbound:
      rules:
        - application: behandlingsflyt
          permissions:
            roles:
              - "oppdater-behandlingsflyt-oppgaver"
        - application: postmottak-backend
          permissions:
            roles:
              - "oppdater-postmottak-oppgaver"
        - application: paw-patrol
        - application: saksbehandling
        {{#if isdev}}
        - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod.yaml
        - application: azure-token-generator # Ikke i prod :)
          namespace: nais
          cluster: dev-gcp
        {{/if}}
    outbound:
      external:
        - host: {{pdl_url}}
        - host: {{veilarb_arena_url}}
        - host: aap-unleash-api.nav.cloud.nais.io
      rules:
        - application: tilgang
        - application: statistikk
        - application: behandlingsflyt
        - application: skjermede-personer-pip
          namespace: nom
        - application: nom-api
          namespace: nom
        - application: veilarboppfolging
          namespace: poao
        - application: syfooversiktsrv
          namespace: teamsykefravr
        - application: logging
          namespace: nais-system
  env:
  {{#each env}}
     - name: {{this.name}}
       value: {{this.value}}
  {{/each}}
  {{#each groups}}
     - name: {{this.name}}
       value: {{this.group}}
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        databases:
          - name: oppgave
