isdev: 0
ingress: https://aap-oppgave.intern.nav.no
pdl_url: pdl-api.prod-fss-pub.nais.io
veilarb_arena_url: veilarbarena.prod-fss-pub.nais.io
unleash_secret: kelvin-unleash-api-token

groups:
  - name: AAP_SAKSBEHANDLER_OPPFOLGING
    group: dc8b0182-1449-445a-833c-1a4620b7c2be
  - name: AAP_SAKSBEHANDLER_NASJONAL
    group: 3a65f41a-b3f3-4b1c-830a-df20ff020980
  - name: AAP_KVALITETSSIKRER
    group: a6bf143f-fee9-41ab-a487-f54503a28de6
  - name: AAP_BESLUTTER
    group: 5763b52f-f16a-483d-8f40-25be9de95c0a
  - name: AAP_PRODUKSJONSSTYRING
    group: 1d61ecf2-fcca-4dbb-ba49-82ab01aef96e
env:
  - name: INTEGRASJON_TILGANG_URL
    value: http://tilgang
  - name: INTEGRASJON_TILGANG_SCOPE
    value: api://prod-gcp.aap.tilgang/.default
  - name: INTEGRASJON_STATISTIKK_URL
    value: http://statistikk
  - name: INTEGRASJON_STATISTIKK_SCOPE
    value: api://prod-gcp.aap.statistikk/.default
  - name: INTEGRASJON_PDL_URL
    value: https://pdl-api.prod-fss-pub.nais.io
  - name: INTEGRASJON_PDL_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default
  - name: INTEGRASJON_NORG_URL
    value: https://norg2.prod-fss-pub.nais.io
  - name: INTEGRASJON_NOM_URL
    value: http://skjermede-personer-pip.nom
  - name: INTEGRASJON_NOM_SCOPE
    value: api://prod-gcp.nom.skjermede-personer-pip/.default
  - name: INTEGRASJON_NOM_API_URL
    value: http://nom-api.nom/graphql
  - name: INTEGRASJON_NOM_API_SCOPE
    value: api://prod-gcp.nom.nom-api/.default
  - name: MS_GRAPH_BASE_URL
    value: https://graph.microsoft.com/v1.0/
  - name: MS_GRAPH_SCOPE
    value: https://graph.microsoft.com/.default
  - name: INTEGRASJON_VEILARBARENA_URL
    value: https://veilarbarena.prod-fss-pub.nais.io
  - name: INTEGRASJON_VEILARBARENA_SCOPE
    value: api://prod-fss.pto.veilarbarena/.default
  - name: INTEGRASJON_VEILARBOPPFOLGING_URL
    value: http://veilarboppfolging.poao
  - name: INTEGRASJON_VEILARBOPPFOLGING_SCOPE
    value: api://prod-gcp.poao.veilarboppfolging/.default
  - name: INTEGRASJON_SYFO_URL
    value: http://syfooversiktsrv.teamsykefravr
  - name: INTEGRASJON_SYFO_SCOPE
    value: api://prod-gcp.teamsykefravr.syfooversiktsrv/.default
  - name: INTEGRASJON_BEHANDLINGSFLYT_URL
    value: http://behandlingsflyt
  - name: INTEGRASJON_BEHANDLINGSFLYT_SCOPE
    value: api://prod-gcp.aap.behandlingsflyt/.default