isdev: 0
pdl_url: pdl-api.prod-fss-pub.nais.io
veilarb_arena_url: veilarbarena.prod-fss-pub.nais.io
env:
  - name: INTEGRASJON_TILGANG_URL
    value: http://tilgang
  - name: INTEGRASJON_TILGANG_SCOPE
    value: api://prod-gcp.aap.tilgang/.default
  - name: INTEGRASJON_STATISTIKK_URL
    value: http://statistikk
  - name: INTEGRASJON_STATISTIKK_SCOPE
    value: api://prod-gcp.aap.statistikk/.default
  - name: INTEGRASJON_PDL_URL
    value: https://pdl-api.prod-fss-pub.nais.io
  - name: INTEGRASJON_PDL_SCOPE
    value: api://prod-fss.pdl.pdl-api/.default
  - name: INTEGRASJON_NORG_URL
    value: https://norg2.prod-fss-pub.nais.io
  - name: INTEGRASJON_NOM_URL
    value: http://skjermede-personer-pip.nom
  - name: INTEGRASJON_NOM_SCOPE
    value: api://prod-gcp.nom.skjermede-personer-pip/.default
  - name: MS_GRAPH_BASE_URL
    value: https://graph.microsoft.com/v1.0/
  - name: MS_GRAPH_SCOPE
    value: https://graph.microsoft.com/.default
  - name: INTEGRASJON_VEILARBARENA_URL
    value: https://veilarbarena.prod-fss-pub.nais.io
  - name: INTEGRASJON_VEILARBARENA_SCOPE
    value: api://prod-fss.pto.veilarbarena/.default
  - name: INTEGRASJON_VEILARBOPPFOLGING_URL
    value: http://veilarboppfolging.poao
  - name: INTEGRASJON_VEILARBOPPFOLGING_SCOPE
    value: api://prod-gcp.poao.veilarboppfolging/.default