package no.nav.aap.oppgave.enhet

enum class Enhet(val kode: String) {
    NAV_VIKAFOSSEN("2103"),
    NAY("4491"),
    NAY_EGNE_ANSATTE("4483"),
    NAV_UTLAND("0393"),
    NAY_UTLAND("4402"),
    NASJONAL_OPPFØLGINGSENHET("4154"),
    NAV_REGION_SUNNFJORD("1476"),
    NAV_KINN("1401"),
    NAV_ASKVOLL("1428"),
    NAV_SUNNFJORD_YTRE_SOGN("1432"),
    NAV_VÆRNES("1783")
}

val NAY_ENHETER = listOf(Enhet.NAY_UTLAND, Enhet.NAY_EGNE_ANSATTE, Enhet.NAY)

val ENHETER_REGION_SUNNFJORD = listOf(Enhet.NAV_KINN, Enhet.NAV_ASKVOLL, Enhet.NAV_SUNNFJORD_YTRE_SOGN)