package no.nav.aap.oppgave.verdityper

enum class ÅrsakTilReturKode {
    MANGELFULL_BEGRUNNELSE,
    MANGLENDE_UTREDNING,
    FEIL_LOVANVENDELSE,
    ANNET,
    SKRIVEFEIL,
    FOR_DETALJERT,
    IKKE_INDIVIDUELL_OG_KONKRET,
    MANGLENDE_JOURNALFØRING,
    MANGLENDE_KILDEHENVISNING,
}
