[versions]
komponenter = "2.0.165"
tilgang = "1.0.242"
behandlingsflytVersjon = "0.0.664"
postmottakVersjon = "6.0.10"

[libraries]
json = { module = "no.nav.aap.kelvin:json", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
ktorOpenapiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }

behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflytVersjon" }
postmottakKontrakt = { module = "no.nav.aap.postmottak:kontrakt", version.ref = "postmottakVersjon" }
tilgangKontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
