
ALTER TABLE OPPGAVE_HISTORIKK ADD COLUMN ENHET VARCHAR(20);
ALTER TABLE OPPGAVE_HISTORIKK ADD COLUMN OPPFOLGINGSENHET VARCHAR(20);
ALTER TABLE OPPGAVE_HISTORIKK ADD COLUMN PAA_VENT_TIL DATE;
ALTER TABLE OPPGAVE_HISTORIKK ADD COLUMN PAA_VENT_AARSAK VARCHAR(80);
