CREATE TABLE TILBAKEKREVING_OPPGAVE_VAR
(
    ID                 BIGSERIAL      NOT NULL PRIMARY KEY,
    OPPGAVE_ID         BIGINT UNIQUE  NOT NULL REFERENCES OPPGAVE (ID) ON DELETE CASCADE,
    TILBAKEKREVING_URL TEXT           NOT NULL,
    BELOP              NUMERIC(18, 2) NOT NULL
);