CREATE INDEX IDX_OPPGAVE_OPPRETTET_TIDSPUNKT ON OPPGAVE (BEHANDLING_OPPRETTET);
CREATE INDEX IDX_OPPGAVE_OPPFOLGINGSENHET ON OPPGAVE (oppfolgingsenhet);
CREATE INDEX IDX_OPPGAVE_ENHET ON OPPGAVE (enhet);
CREATE INDEX IDX_OPPGAVE_STATUS ON OPPGAVE (status);
CREATE INDEX IDX_OPPGAVE_RESERVERT_AV ON OPPGAVE (reservert_av);