ALTER TABLE OPPGAVE
    ADD COLUMN SISTE_PAA_VENT_AARSAK    TEXT,
    ADD COLUMN SISTE_PAA_VENT_TIL       DATE,
    ADD COLUMN SISTE_VENTE_BEGRUNNELSE  TEXT;

-- Backfill fra gjeldende på-vent-info der oppgaven fortsatt er på vent
UPDATE OPPGAVE
SET SISTE_PAA_VENT_AARSAK   = PAA_VENT_AARSAK,
    SISTE_PAA_VENT_TIL       = PAA_VENT_TIL,
    SISTE_VENTE_BEGRUNNELSE  = VENTE_BEGRUNNELSE
WHERE PAA_VENT_AARSAK IS NOT NULL;

-- Backfill fra historikk for oppgaver som har vært på vent, men ikke er det nå
UPDATE OPPGAVE o
SET SISTE_PAA_VENT_AARSAK   = h.PAA_VENT_AARSAK,
    SISTE_PAA_VENT_TIL       = h.PAA_VENT_TIL,
    SISTE_VENTE_BEGRUNNELSE  = h.VENTE_BEGRUNNELSE
FROM (
    SELECT DISTINCT ON (OPPGAVE_ID)
        OPPGAVE_ID,
        PAA_VENT_AARSAK,
        PAA_VENT_TIL,
        VENTE_BEGRUNNELSE
    FROM OPPGAVE_HISTORIKK
    WHERE PAA_VENT_AARSAK IS NOT NULL
    ORDER BY OPPGAVE_ID, ENDRET_TIDSPUNKT DESC NULLS LAST, ID DESC
) h
WHERE o.ID = h.OPPGAVE_ID
  AND o.SISTE_PAA_VENT_AARSAK IS NULL;
