ALTER TABLE FILTER ADD COLUMN TYPE TEXT;
UPDATE FILTER SET TYPE = 'GENERELL';
ALTER TABLE FILTER ALTER COLUMN TYPE SET NOT NULL;

UPDATE FILTER SET TYPE = 'KVALITETSSIKRING' WHERE (id = 25 AND navn = 'Kvalitetssikrer') OR (id = 6  AND navn = 'Kvalitetssikrer');

UPDATE FILTER SET TYPE = 'ALLE_OPPGAVER' WHERE (id = 27 AND navn = 'Alle oppgaver') OR (id = 8  AND navn = 'Alle oppgaver');

