ALTER TABLE OPPGAVE_HISTORIKK
    ADD COLUMN VENTE_BEGRUNNELSE TEXT;

UPDATE OPPGAVE_HISTORIKK historikk
SET VENTE_BEGRUNNELSE = oppgave.VENTE_BEGRUNNELSE
FROM OPPGAVE oppgave
WHERE historikk.OPPGAVE_ID = oppgave.ID
  AND historikk.PAA_VENT_TIL IS NOT DISTINCT FROM oppgave.PAA_VENT_TIL
  AND historikk.PAA_VENT_AARSAK IS NOT DISTINCT FROM oppgave.PAA_VENT_AARSAK
  AND historikk.VENTE_BEGRUNNELSE IS NULL
  AND oppgave.VENTE_BEGRUNNELSE IS NOT NULL;

CREATE OR REPLACE FUNCTION oppdater_oppgave_historikk()
    RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO OPPGAVE_HISTORIKK (
        OPPGAVE_ID, STATUS,
        RESERVERT_AV,
        RESERVERT_TIDSPUNKT,
        ENHET,
        OPPFOLGINGSENHET,
        PAA_VENT_TIL,
        PAA_VENT_AARSAK,
        ENDRET_AV,
        ENDRET_TIDSPUNKT,
        VEILEDER_ARBEID,
        VEILEDER_SYKDOM,
        VENTE_BEGRUNNELSE
    )
    VALUES (
               NEW.id,
               NEW.STATUS,
               NEW.RESERVERT_AV,
               NEW.RESERVERT_TIDSPUNKT,
               NEW.ENHET,
               NEW.OPPFOLGINGSENHET,
               NEW.PAA_VENT_TIL,
               NEW.PAA_VENT_AARSAK,
               NEW.ENDRET_AV,
               NEW.ENDRET_TIDSPUNKT,
               NEW.VEILEDER_ARBEID,
               NEW.VEILEDER_SYKDOM,
               NEW.VENTE_BEGRUNNELSE
           );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
