ALTER TABLE FILTER ADD COLUMN TYPE VARCHAR(100);

UPDATE FILTER SET TYPE = 'KVALITETSSIKRING' WHERE id = ( SELECT id WHERE navn = 'Kvalitetssikrer' ORDER BY id ASC LIMIT 1 );

UPDATE FILTER SET TYPE = 'ALLE_OPPGAVER' WHERE id = ( SELECT id WHERE navn = 'Alle oppgaver' ORDER BY id ASC LIMIT 1 );

