CREATE TABLE DIALOG_MED_BEHANDLER
(
    ID                  BIGSERIAL     NOT NULL PRIMARY KEY,
    BEHANDLING_REF      UUID          NOT NULL,
    TYPE                VARCHAR(50)   NOT NULL,
    OPPRETTET_TIDSPUNKT TIMESTAMP(3)  NOT NULL,
    OPPRETTET_AV        VARCHAR(20)   NOT NULL
);

CREATE INDEX IDX_DIALOG_MED_BEHANDLER_BEHANDLING_REF ON DIALOG_MED_BEHANDLER (BEHANDLING_REF);

